name: angulardart_transformer_e2e_app
version: 0.0.1
authors:
- Diana Salsbury <diana.salsburyd@gmail.com>
- Chirayu Krishnappa <chirayu@chirayuk.com>
description: Specs for AngularDart examples.
dependencies:
  angular:
    path: ../
  di: '>=2.0.1 <3.0.0'
transformers:
- angular
